services:
  mysql:
    image: public.ecr.aws/docker/library/mysql:8.0
    container_name: at_mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ishocon1
    ports:
      - "3306:3306"
    networks:
      - kamesan

  adminer:
    image: public.ecr.aws/docker/library/adminer:standalone
    container_name: at_adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - "1234:8080"
    networks:
      - kamesan

  redis:
    image: public.ecr.aws/docker/library/redis:7.0
    container_name: at_redis
    ports:
      - "6379:6379"
    networks:
      - kamesan

  redisinsight:
    image: redis/redisinsight
    container_name: at_redisinsight
    ports:
      - "5540:5540"
    networks:
      - kamesan

  webapp:
    image: ruby
    environment:
      - REDIS_HOST=redis
      - ISHOCON1_DB_HOST=at_mysql
    ports:
      - "8080:8080"

    volumes:
      - ./:/app
    working_dir: /app

    command: |-
      sh -c '
      rm /tmp/unicorn.pid;
      bundle install;
      bundle exec unicorn -c unicorn_config.rb
      '

      echo meow
    networks:
      - kamesan

networks:
  kamesan: